### PR TITLE
README.md: s/neq/ne/

### PR DESCRIPTION
**Pull request by rrika**

### CODE REVIEW

**Comment by mpreiner** [comment]
Good catch! Thanks for pointing this out. I fixed it in the parser ( e97fc9c) since the format described in the paper also uses `neq` instead of `ne`.

**Comment by rrika** [comment]
examples/btorsim/ponylink-slaveTXlen-sat.btor2 still uses `ne`

**Comment by rrika** [comment]
I know it's hard to amend the paper but this would make `neq` the only operator that has been renamed vs. btor1.

**Comment by mpreiner** [comment]
Yes, but imo this is not an issue (we removed other keywords from BTOR1) and we don't aim for backwards compatibility anyways since we introduced sorts. Thanks for point out the example, will fix it!

**Pull request closed without merging**
